import type { Student, StudentStatus } from '../@types';

export const COMPUTER_ENGINEERING_COURSES: string[] = [
  'Data Structures & Algorithms',
  'Computer Networks',
  'Operating Systems',
  'Database Management Systems',
  'Object-Oriented Programming',
  'Computer Architecture',
  'Software Engineering',
  'Machine Learning Fundamentals',
  'Web Development',
  'Cybersecurity Fundamentals',
  'Discrete Mathematics for CS',
  'Cloud Computing',
];

export const STUDENT_STATUS_TABS: Array<{ value: StudentStatus; label: string }> = [
  { value: 'active', label: 'Active Students' },
  { value: 'deactivated', label: 'Deactivated Students' },
  { value: 'deleted', label: 'Deleted Students' },
];

export const MOCK_STUDENTS: Student[] = [
  {
    id: '1',
    studentId: 'STU-2401',
    firstName: 'Ada',
    lastName: 'Lovelace',
    email: 'ada.lovelace@example.com',
    phone: '(415) 555-0134',
    course: 'Data Structures & Algorithms',
    assignedOn: '2024-01-15',
    status: 'active',
  },
  {
    id: '2',
    studentId: 'STU-2402',
    firstName: 'Alan',
    lastName: 'Turing',
    email: 'alan.turing@example.com',
    phone: '(415) 555-0198',
    course: 'Computer Architecture',
    assignedOn: '2024-01-18',
    status: 'active',
  },
  {
    id: '3',
    studentId: 'STU-2403',
    firstName: 'Grace',
    lastName: 'Hopper',
    email: 'grace.hopper@example.com',
    phone: '(628) 555-0112',
    course: 'Operating Systems',
    assignedOn: '2024-02-02',
    status: 'active',
  },
  {
    id: '4',
    studentId: 'STU-2404',
    firstName: 'Katherine',
    lastName: 'Johnson',
    email: 'katherine.johnson@example.com',
    phone: '(628) 555-0176',
    course: 'Machine Learning Fundamentals',
    assignedOn: '2024-02-10',
    status: 'active',
  },
  {
    id: '5',
    studentId: 'STU-2405',
    firstName: 'Margaret',
    lastName: 'Hamilton',
    email: 'margaret.hamilton@example.com',
    phone: '(510) 555-0143',
    course: 'Software Engineering',
    assignedOn: '2024-02-14',
    status: 'active',
  },
  {
    id: '6',
    studentId: 'STU-2406',
    firstName: 'Tim',
    lastName: 'Berners-Lee',
    email: 'tim.bl@example.com',
    phone: '(510) 555-0187',
    course: 'Web Development',
    assignedOn: '2024-03-01',
    status: 'active',
  },
  {
    id: '7',
    studentId: 'STU-2407',
    firstName: 'Radia',
    lastName: 'Perlman',
    email: 'radia.perlman@example.com',
    phone: '(650) 555-0121',
    course: 'Computer Networks',
    assignedOn: '2024-03-05',
    status: 'active',
  },
  {
    id: '8',
    studentId: 'STU-2408',
    firstName: 'Edsger',
    lastName: 'Dijkstra',
    email: 'edsger.dijkstra@example.com',
    phone: '(650) 555-0165',
    course: 'Discrete Mathematics for CS',
    assignedOn: '2024-03-12',
    status: 'active',
  },
  {
    id: '9',
    studentId: 'STU-2409',
    firstName: 'Barbara',
    lastName: 'Liskov',
    email: 'barbara.liskov@example.com',
    phone: '(408) 555-0109',
    course: 'Object-Oriented Programming',
    assignedOn: '2024-03-20',
    status: 'active',
  },
  {
    id: '10',
    studentId: 'STU-2410',
    firstName: 'Vint',
    lastName: 'Cerf',
    email: 'vint.cerf@example.com',
    phone: '(408) 555-0154',
    course: 'Cybersecurity Fundamentals',
    assignedOn: '2024-01-22',
    status: 'deactivated',
  },
  {
    id: '11',
    studentId: 'STU-2411',
    firstName: 'Frances',
    lastName: 'Allen',
    email: 'frances.allen@example.com',
    phone: '(925) 555-0132',
    course: 'Cloud Computing',
    assignedOn: '2024-02-08',
    status: 'deactivated',
  },
  {
    id: '12',
    studentId: 'STU-2412',
    firstName: 'John',
    lastName: 'McCarthy',
    email: 'john.mccarthy@example.com',
    phone: '(925) 555-0177',
    course: 'Database Management Systems',
    assignedOn: '2024-02-25',
    status: 'deactivated',
  },
  {
    id: '13',
    studentId: 'STU-2413',
    firstName: 'Donald',
    lastName: 'Knuth',
    email: 'donald.knuth@example.com',
    phone: '(707) 555-0148',
    course: 'Data Structures & Algorithms',
    assignedOn: '2023-11-10',
    status: 'deleted',
  },
  {
    id: '14',
    studentId: 'STU-2414',
    firstName: 'Ken',
    lastName: 'Thompson',
    email: 'ken.thompson@example.com',
    phone: '(707) 555-0193',
    course: 'Operating Systems',
    assignedOn: '2023-12-01',
    status: 'deleted',
  },
  {
    id: '15',
    studentId: 'STU-2415',
    firstName: 'Dennis',
    lastName: 'Ritchie',
    email: 'dennis.ritchie@example.com',
    phone: '(831) 555-0126',
    course: 'Computer Architecture',
    assignedOn: '2023-12-15',
    status: 'deleted',
  },
];
